export default [
  {
    id: 1,
    name: 'Write clean code',
    type: 'sweatshirt',
    description: 'Lorem ipsum dolor sit amet, a Lev loh',
    price: 1337,
    purchases: 0,
    varieties: [
      {
        id: 0,
        color: '#FF0',
        images: ['/images/store/sweatshirt.png'],
        sizes: {
          XS: 1,
          S: 0,
          M: 4,
          L: 1,
          XL: 1,
          XXL: 2,
        },
      },
      {
        id: 1,
        color: '#00FF00',
        images: ['/images/store/sweatshirt.png'],
        sizes: {
          XS: 11,
          S: 0,
          M: 2,
          L: 0,
          XL: 123,
          XXL: 2,
        },
      },
    ],
  },
  {
    id: 2,
    name: 'ASCII Whale',
    type: 'T-Shirt',
    description: 'Lorem ipsum dolor sit amet, a Lev kakaha',
    price: 1337,
    purchases: 0,
    varieties: [
      {
        id: 0,
        color: '#0000FF',
        images: ['/images/store/tshirt.png', '/images/store/sweatshirt.png'],
        sizes: {},
      },
      {
        id: 1,
        color: '#000000',
        images: ['/images/store/tshirt.png'],
        sizes: {},
      },
      {
        id: 2,
        color: '#FFFFFF',
        images: ['/images/store/tshirt.png'],
        sizes: {},
      },
      {
        id: 3,
        color: '#CC00CC',
        images: ['/images/store/sweatshirt.png', '/images/store/tshirt.png'],
        sizes: {},
      },
    ],
  },
  {
    id: 3,
    name: 'UI Umbrella',
    type: '',
    description: 'Lorem ipsum dolor sit amet, a Lev kakaha',
    price: 201,
    purchases: 0,
    varieties: [
      {
        id: 0,
        color: '#FF0000',
        images: ['/images/store/umbrella.png'],
        sizes: {},
      },
    ],
  },
  {
    id: 4,
    name: 'Write clean code',
    type: 'sweatshirt',
    description: 'Lorem ipsum dolor sit amet, a Lev loh',
    price: 1337,
    purchases: 0,
    varieties: [
      {
        id: 0,
        color: '#00FF00',
        images: ['/images/store/sweatshirt.png'],
        sizes: {},
      },
      {
        id: 1,
        color: '#FF0000',
        images: ['/images/store/sweatshirt.png'],
        sizes: {},
      },
    ],
  },
  {
    id: 5,
    name: 'ASCII Whale',
    type: 'T-Shirt',
    description: 'Lorem ipsum dolor sit amet, a Lev kakaha',
    price: 1337,
    purchases: 0,
    varieties: [
      {
        id: 0,
        color: '#FF0000',
        images: ['/images/store/tshirt.png'],
        sizes: {},
      },
    ],
  },
  {
    id: 6,
    name: 'UI Umbrella',
    type: '',
    description: 'Lorem ipsum dolor sit amet, a Lev kakaha',
    price: 201,
    purchases: 0,
    varieties: [
      {
        id: 0,
        color: '#FF0000',
        images: ['/images/store/umbrella.png'],
        sizes: {},
      },
    ],
  },
];
