export default [
  {
    id: 1,
    img: '/images/projects/chess-club.png',
    title: 'Chess Tournament',
    date: {
      start: new Date('2019-07-05T00:00:00'),
      end: new Date('2019-07-05T00:00:00'),
    },
    organizer: '319',
    activities: [
      {
        name: 'Catering',
        description: 'You will do some catering. Do you even know what is it?',
        reward: 70,
        worktime: 5,
        isFixed: false,
        competences: ['healthy lifestyle & wellbeing', 'creativity', 'teamwork'],
      },
      {
        name: 'Video Editing',
        description: 'You will have to manage editing of 50GB of video materials to produce a 1-minute video for InnoStudents insta',
        reward: 7000,
        worktime: null,
        isFixed: true,
        competences: ['proactivity', 'creativity', 'learning to Learn'],
      },
      {
        name: 'Content writing',
        description: 'Writing 5 good-quality post-releases after the event',
        rewardRate: 1200,
        worktime: null,
        isFixed: true,
        competences: ['creativity', 'teamwork'],
      },
      {
        name: 'Toilet pointer',
        description: 'You\'re a volunteer now. Stand in the hall and point visitors to a toilet',
        rewardRate: 70,
        worktime: 24,
        isFixed: false,
        competences: ['communication'],
      },
      {
        name: 'Just standing',
        description: 'Simple standing for 10 hours. Because you\'re a volunteer',
        rewardRate: 70,
        worktime: 10,
        isFixed: false,
        competences: ['healthy lifestyle & wellbeing'],
      },
    ],
    spots: 3,
    competences: ['creativity', 'critical thinking', 'leadership', 'conflict aversion', 'communication', 'some other skill'],
    status: 'Unpublished, awaiting review',
  },
  {
    id: 2,
    img: '/images/projects/arro.png',
    title: 'All-Russian Robotics Olympiad',
    date: {
      start: new Date('2019-07-05T00:00:00'),
      end: new Date('2019-07-08T00:00:00'),
    },
    organizer: 'Olympiads dept.',
    activities: [
      {
        name: 'Content writing',
        description: 'Writing 5 good-quality post-releases after the event',
        rewardRate: 1200,
        worktime: null,
        isFixed: true,
        competences: ['creativity', 'teamwork'],
      },
      {
        name: 'Toilet pointer',
        description: 'You\'re a volunteer now. Stand in the hall and point visitors to a toilet',
        rewardRate: 70,
        worktime: 24,
        isFixed: false,
        competences: ['communication'],
      },
      {
        name: 'Just standing',
        description: 'Simple standing for 10 hours. Because you\'re a volunteer',
        rewardRate: 70,
        worktime: 10,
        isFixed: false,
        competences: ['healthy lifestyle & wellbeing'],
      },
    ],
    spots: 5,
    competences: ['conflict aversion', 'communication'],
    status: 'Modified, awaiting review',
  },
];
